<h3><a href="/diapos/" title="Retour à la liste des albums"><i class="icon-arrow-left icon-white"></i></a>{{displayTitle}}</h3>
<ul class="thumbnails">
{{#each entry}}
    <li>
        <div class="diapo" data-title="{{title}}">
            <div style="width:{{thumbs.0.height}}px; height:{{thumbs.0.width}}px">
                <a href="{{src}}" title="Agrandir">
                    <img src="{{thumbs.0.url}}" width="{{thumbs.0.width}}" height="{{thumbs.0.height}}" style="width:{{thumbs.0.width}}px; height:{{thumbs.0.height}}px" />
                </a>
            </div>
       </div>
        <div>{{title}}</div>
    </li>
{{/each}}
</ul>
<div id="myModal" class="modal hide" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
<div class="modal-header">
<button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
<h3></h3>
</div>
<div class="modal-body"></div>
</div>