<!-- <div id="carousel" class="carousel slide"> -->
  <!-- Carousel items -->
  <!-- <div class="carousel-inner"> -->
    <!-- <div class="item active" data-title="{{diap.title}}"> -->
<a class="carousel-control left" data-slide="prev">&lsaquo;</a>
<img src="{{diap.src}}" width="{{width}}" height="{{height}}" style="width:{{width}}px; height:{{height}}px" />
<a class="carousel-control right" data-slide="next">&rsaquo;</a>
        <!-- </div> -->
  <!-- </div> -->
  <!-- Carousel nav -->
<!-- </div> -->
